services:
  postgres:
    container_name: devops-backend-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: devops-backend
      PGDATA: /var/lib/postgresql/data